### PR TITLE
fix: Remove Terraform module code from project

### PR DESCRIPTION
**Pull request by bryantbiggs**
### What does this PR do?

- Remove Terraform module code from project
- Bump addons modules to latest `v0.2.0`
- Update `elastic-fabric-adapter` example to use new addons module

### Motivation

- Work towards v5

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by rodrigobersa — APPROVED** [review]

**Comment by Almenon** [comment]
Where was the code moved to? I don't see it in https://github.com/aws-ia/terraform-aws-eks-blueprints-addons or https://github.com/aws-ia/terraform-aws-eks-blueprints-addon

**Comment by bryantbiggs** [comment]
@Almenon - which code are you referring to exactly?

**Comment by Almenon** [comment]
Sorry, should have specified. I'm referring to code
like modules/kubernetes-addons/external-dns/main.tf

**Comment by bryantbiggs** [comment]
External DNS is supported in the new addons module https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/936a488770048ee3caf037e21270cac8e0bcae16/main.tf#L1830-L1937

**Comment by Almenon** [comment]
Ahhh, I see. It's all in one giant file, `main.tf`. Most of the logic in that file is abstracted away by reuse of https://github.com/aws-ia/terraform-aws-eks-blueprints-addon. Thanks!

**Pull request merged**
