### PR TITLE
feat: Consul addon

### LINKED ISSUE #443: [ADDON] - Consul

### PR DESCRIPTION
**Pull request by florentio**
### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

Haschicorp Consul addons 

### Motivation

- Resolves #443

### More

- [x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [x] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [x] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs require a new example and/or doc page. In general:
- Use an existing example when possible to demonstrate a new addons usage
- A new docs page under `docs/add-ons/*` is required for new a new addon

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by david-yu** [comment]
Hi @florentio , Consul PM here. Would it be possible to use Consul K8s 1.0 when it releases sometime next month? That might be a good release to start with as there will be a lot of breaking changes coming within a month or so. In addition, I would recommend setting server.replicas to 3 via the Helm chart if you are looking to deploy Consul in production on EKS.

**Comment by bryantbiggs** [comment]
@david-yu would this be something that Hashi wants to create similar to the Vault addon https://github.com/hashicorp/terraform-aws-hashicorp-vault-eks-addon and then we utilize that addon here in the project (ref [Vault](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/2cd89ecc5bf110c48efffe0e8dad77703f9d8b04/modules/kubernetes-addons/main.tf#L389-L398))?

**Comment by bryantbiggs** [comment]
closing for now until Consul 1.0 is released

**Comment by YoSuperG** [comment]
Consul 1.14 | Consul k8s 1.0 ETA Nov 17th, thx @florentio.

**Comment by bryantbiggs** [comment]
FYI - looks like this is now GA https://www.hashicorp.com/blog/consul-1-14-ga-announcing-simplified-service-mesh-deployments 🎉

**Review by bryantbiggs — APPROVED** [review]
Thank you for your patience @florentio !

**Pull request merged**
