### PR TITLE
chore: kubernetes_service_account_v1 secret always show diff

### PR DESCRIPTION
**Pull request by kahirokunn**
issue: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1043#issuecomment-1134245891

### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

### More

- [x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by askulkarni2** [comment]
@kahirokunn thanks for the PR. Can you please open an issue for tracking and add steps to reproduce as well as results of your testing after applying this fix?

**Comment by kahirokunn** [comment]
I forgot. I will do it.

**Comment by kahirokunn** [comment]
Late

**Comment by bryantbiggs** [comment]
closing for now since we need to understand if there are any consequences to ignoring these changes long term

**Pull request closed without merging**
