### PR TITLE
[bugfix]: #532: Have teams module honor permissions boundary

### LINKED ISSUE #532: [Bug]: IAM permissions boundary not passed down to teams add on
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

4.0.4

### What is your environment, configuration and the example used?

If you build a cluster and set up a team (just like in the documentation here: https://aws-ia.github.io/terraform-aws-eks-blueprints/teams/), but the AWS role you are running the apply with requires a permissions boundary to be set, it fails with an IAM permissions error. This is because while the main blueprints module supports the addition of a permissions boundary (https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/79724fbcc961140b594683d2bd152fa3152b9181/main.tf#L44), the call to the teams module doesn't have it, which causes the boundary to not get passed in (https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/79724fbcc961140b594683d2bd152fa3152b9181/main.tf#L141)

### What did you do and What did you see instead?

Would have expected a clean apply. Instead, the teams apply fails with errors similar to this: 

`│ Error: failed creating IAM Role (lab-srhoton-cluster-6-infra-team-blue-Access): AccessDenied: User: arn:aws:sts::[account number]:assumed-role/[role] is not authorized to perform: iam:CreateRole on resource: [role] because no identity-based policy allows the iam:CreateRole action
│       status code: 403, request id: 2944cfde-10f7-4130-88e6-3e85b154990f
`

### Additional Information

```shell
Happy to submit a PR to fix this if you'd like.
```

### PR DESCRIPTION
**Pull request by srhoton**
### What does this PR do?

This fixes bug #532 , and makes the teams module honor the permissions boundary in the main blueprints module. 

### Motivation

We hit this bug testing blueprints, and thought it was a pretty straightforward fix. 
- Closes #532 

### More

- [ x ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by askulkarni2 — CHANGES_REQUESTED** [review]
@srhoton thank you for this PR. Its looking good. There are some CI failures related to `terraform format`. You should be able to see them [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/runs/6397692328?check_suite_focus=true).

**Comment by srhoton** [comment]
@askulkarni2 - Sorry! I should have caught that. Formatting should be fixed now.

**Comment by bryantbiggs** [comment]
@srhoton you'll also need to update the docs for the added variable. The safest bet is to run `pre-commit run -a` which will run all checks, or the fastest route for your change is just `pre-commit run terraform_docs -a`

**Review by bryantbiggs — APPROVED** [review]
Thank you for the PR!

**Review by kcoleman731 — APPROVED** [review]

**Pull request merged**
