### PR TITLE
Aws codepipeline

### PR DESCRIPTION
**Pull request by aromal-amzn**
### What does this PR do?

Setting up AWS CodePipeline, AWS CodeBuild projects and other requirements using terraform IaC which shows an example of how to automate the validation, plan, approval based apply and destroy of terraform code.

### More

- [X] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [X] Yes, I have added a new example under [examples](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/ssp-eks-add-ons) repo (if applicable)
- [X] Yes, I have updated the [docs](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/docs) for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [x] E2E Test successfully complete before merge?

### Additional Notes

1. Passed tflint --> tflint --only=terraform_deprecated_interpolation --only=terraform_deprecated_index --only=terraform_unused_declarations --only=terraform_comment_syntax --only=terraform_documented_outputs --only=terraform_documented_variables --only=terraform_typed_variables --only=terraform_module_pinned_source --only=terraform_naming_convention --only=terraform_required_version --only=terraform_required_providers --only=terraform_standard_module_structure --only=terraform_workspace_remote

2. tfsec
  results
  ──────────────────────────────────────────
  passed               12
  ignored              0
  critical             0
  high                 0
  medium               0
  low                  0

3. Kics Scan - kics scan -p . --exclude-queries 568a4d22-3517-44a6-a7ad-6a7eed88722c,6726dcc0-5ff5-459d-b473-a780bef7665c,c5b31ab9-0f26-4a49-b8aa-4cc064392f4d,f861041c-8c9f-4156-acfc-5e6e524f5884
Results Summary:
HIGH: 0
MEDIUM: 0
LOW: 0
INFO: 7
TOTAL: 7

4. checkov - checkov -d ./ --skip-check CKV_AWS_144
Passed checks: 23, Failed checks: 0, Skipped checks: 0

5.  terraform validate
Success! The configuration is valid.

### CODE REVIEW

**Comment by kcoleman731** [comment]
@aromal-amzn love the work here. Thank you for the contribution. We should consider if CodeBuild modules themselves should live in a dedicated repo. I think customer could benefit from these modules outside of EKS Blueprints.

**Comment by aromal-amzn** [comment]
> @aromal-amzn love the work here. Thank you for the contribution. We should consider if CodeBuild modules themselves should live in a dedicated repo. I think customer could benefit from these modules outside of EKS Blueprints.



> @aromal-amzn love the work here. Thank you for the contribution. We should consider if CodeBuild modules themselves should live in a dedicated repo. I think customer could benefit from these modules outside of EKS Blueprints.

@kcoleman731 - This is a custom tailored codebuild module for our specific use case of handling terraform deployments. There is already a codebuild module in aws-ia which is published in the terraform registry as well. https://github.com/aws-ia/terraform-aws-codebuild. I will definetly explore the possibilities though. Meanwhile, just wanted to check if any rework/updates/enhancements are required on this PR.

**Comment by bryantbiggs** [comment]
@aromal-amzn is there any reason to not use the https://github.com/aws-ia/terraform-aws-codebuild module - or perhaps, would your suggested changes be better suited for that project? This project is tailored towards provisioning and bootstrapping EKS clusters whereas Codebuild/Codepipeline is currently outside the scope of this project

**Comment by aromal-amzn** [comment]
> @aromal-amzn is there any reason to not use the https://github.com/aws-ia/terraform-aws-codebuild module - or perhaps, would your suggested changes be better suited for that project? This project is tailored towards provisioning and bootstrapping EKS clusters whereas Codebuild/Codepipeline is currently outside the scope of this project

@bryantbiggs - I had evaluated that module and it still needs customization for our use-case. That particular module is preferred for creating standalone codebuild projects with GITHUB as source, where as we were targeting to create Codebuild projects integrated and triggered by the codepipeline which calls the different codebuild projects (validate{tflint,tfsec,checkov scans etc.}, plan, apply{approval based} and destroy{approval based}, for which the source would be s3 bucket which will be used to propagate the artifacts throught the stages (starting with the checkout of Codecommit repository).

**Comment by bryantbiggs** [comment]
> > @aromal-amzn is there any reason to not use the [aws-ia/terraform-aws-codebuild](https://github.com/aws-ia/terraform-aws-codebuild) module - or perhaps, would your suggested changes be better suited for that project? This project is tailored towards provisioning and bootstrapping EKS clusters whereas Codebuild/Codepipeline is currently outside the scope of this project
> 
> @bryantbiggs - I had evaluated that module and it still needs customization for our use-case. That particular module is preferred for creating standalone codebuild projects with GITHUB as source, where as we were targeting to create Codebuild projects integrated and triggered by the codepipeline which calls the different codebuild projects (validate{tflint,tfsec,checkov scans etc.}, plan, apply{approval based} and destroy{approval based}, for which the source would be s3 bucket which will be used to propagate the artifacts throught the stages (starting with the checkout of Codecommit repository).

Understood. It sounds like you are looking to create a custom codebuild/codepipeline module for your use case to which I suggest look at creating a new repository/project to host that. For now though, this is outside the scope of this project so we're going to close this PR

**Pull request closed without merging**
