### PR TITLE
fix: Remove crossplane example from e2e workflows

### PR DESCRIPTION
**Pull request by Zvikan**
### What does this PR do?
- removes crossplane from e2e GH workflows (parallel and destroy)
-
🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

### Motivation

- Post https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1150 crossplane TF files doesn't exists in this repo therefore we can safety remove it from the e2e workflows.

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs require a new example and/or doc page. In general:
- Use an existing example when possible to demonstrate a new addons usage
- A new docs page under `docs/add-ons/*` is required for new a new addon

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by askulkarni2 — APPROVED** [review]

**Comment by askulkarni2** [comment]
Thanks, I know I was missing something :)

**Review by vara-bonthu — APPROVED** [review]

**Review by bryantbiggs — APPROVED** [review]

**Review by csantanapr — APPROVED** [review]

**Comment by csantanapr** [comment]
What's wrong with crossplane in 2e2, your going to crate an issue with the details?

**Comment by Zvikan** [comment]
> What's wrong with crossplane in 2e2, your going to crate an issue with the details?

the crossplane example doesn't exists anymore, see the motivation section for this issue

**Comment by timblaktu** [comment]
@Zvikan I align with @csantanapr. I've followed the entire trail of issues and PRs and although it's clear that what you're doing here is removing the crossplane example from e2e workflow because the crossplane example doesn't exist anymore, it's not at all clear why the crossplane example has been moved from a blueprints example into [a separate dedicated repo over at awslabs](https://github.com/awslabs/crossplane-on-eks). 

The premise of #1150 on the surface is to fix the crossplane example by making [this change](https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1150/files#diff-b465d6fbee9bdc799eb3a11f859d9977dcb13d6328b64da5d8b7cdcfeec4aaddL7) to point at the new source location for the provider package over at the new upbound marketplace, but that PR also deletes the example without comment.

**Pull request merged**
