### PR TITLE
feat: Add Istio Ambient mode example and update version to 1.22

### LINKED ISSUE #1955: Add Istio Ambient Mode Example and Update to 1.22
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

The outcome I'm trying to achieve is to enhance the repository by adding an example demonstrating how to provision an EKS cluster with Istio in `Ambient` mode. Additionally, updating the version to 1.22 is necessary.

#### Describe the solution you would like

I would like to propose adding documentation and Terraform scripts for deploying an EKS cluster with Istio in `Ambient` mode. This includes detailed instructions for installing Istio in `Ambient` mode.

#### Describe alternatives you have considered

An alternative approach could be to include comments within the `main.tf` file explaining the ambient settings and how users can customize them according to their requirements.

#### Additional context

The addition of this example will enhance the repository's documentation and provide users with a practical guide for deploying Istio in `Ambient` mode on Amazon EKS. Additionally, updating the version to 1.22 ensures that users have access to the latest features and improvements in Istio.

### PR DESCRIPTION
**Pull request by PetrMc**
# Description

### Motivation and Context

- Resolves #1955 

### How was this change tested?

- [X] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [X] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR

### CODE REVIEW

**Comment by PetrMc** [comment]
@praseedasathaye - we were able to merge two modes back to one directory by introducing `enable_ambient_mode` variable. Would love to have your feedback. Thanks!

**Comment by bryantbiggs** [comment]
FYI - patterns are static, not dynamic like modules

**Comment by PetrMc** [comment]
@bryantbiggs - how would I test if my changes work? `terraform` commands are successful in my tests, but you're saying patterns are applied different way? Can you point me into the right direction? Thanks!

**Comment by bryantbiggs** [comment]
thank you @PetrMc for the PR - we will close this in favor of https://github.com/aws-samples/istio-on-eks/pull/75

**Comment by PetrMc** [comment]
Thanks @bryantbiggs it should be some technical way to implement it. Will `locals` work? then we need to instruct users to change local variable inside of `main.tf` to deploy `ambient` mode. I'll do some research and will get back to it by the end of the week. If nothing works - we still need to update PR when https://github.com/aws-samples/istio-on-eks/pull/75 is merged.

**Comment by bryantbiggs** [comment]
I'm not quite following - once the pattern is provided at https://github.com/aws-samples/istio-on-eks, there isn't any further action required here

and more broadly, patterns are not dynamic so we don't provide variables to change or modify the behavior. what you see is what you get

**Comment by PetrMc** [comment]
Thanks @bryantbiggs. I noticed that the [README.md](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/istio#readme) currently does not reference [Istio on EKS](https://github.com/aws-samples/istio-on-eks). If adding the example to the blueprint repo is not feasible, it would be helpful for the [README.md](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/istio#readme) to mention `Ambient Mode` and include a link to the [Istio on EKS](https://github.com/aws-samples/istio-on-eks). Additionally, I've identified and fixed several improvements within the [README.md](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/istio#readme).

I'd appreciate it if you could review [this locals variable implementation](https://github.com/PetrMc/terraform-aws-eks-blueprints/blob/7577d4c09eb570eff8132d75adc30129d7b90a72/patterns/istio/main.tf#L43-L44) and let me know if the PR can be accepted.

Thank you for your consideration.

**Pull request closed without merging**
