### PR TITLE
fix: Keep multi-repo consistent with single-repo for helm values configuration.

### LINKED ISSUE #1722: passing helm values configuration for multi-repo app from terraform is not working
## Description

Currently the helm values from terraform are ignored or not passed to multi-repo app due to the difference in the way they are passed and the way it is expected by the multi-repo app.

In the blue-green-update example, helm values for the multi-repo app of apps are passed from terraform at this [line](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/a166b8d06f38170903b99a701f0ea788916dfa4c/examples/blue-green-upgrade/modules/eks_cluster/main.tf#L116) for nodejs. 

        apps = {
          ecsdemoNodejs = {
            replicaCount = "9"
            nodeSelector = {
              "karpenter.sh/provisioner-name" = "default"
            }
            tolerations = [
              {
                key      = "karpenter"
                operator = "Exists"
                effect   = "NoSchedule"
              }
....
For frontend app it is at this [line](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/a166b8d06f38170903b99a701f0ea788916dfa4c/examples/blue-green-upgrade/modules/eks_cluster/main.tf#L172)

          ecsdemoFrontend = {
            repoURL        = "https://github.com/allamand/ecsdemo-frontend"
            targetRevision = "main"
            image = {
              repository = "public.ecr.aws/seb-demo/ecsdemo-frontend"
              tag        = "latest"
            }
            ingress = {
              enabled   = "true"
              className = "alb"

But in the workloads repo for multi-repo app of apps, the helm values are expected in a different format.  For example for nodejs app, this [line](https://github.com/aws-samples/eks-blueprints-workloads/blob/cb96cada0e27a8d0f8f09a935d230cdee043e10c/multi-repo/argo-app-of-apps/dev/values.yaml#L40) expects in this format

      helm:
        parameters:
        - name: replicaCount
          value: '3'

But for frontend, this [line](https://github.com/aws-samples/eks-blueprints-workloads/blob/cb96cada0e27a8d0f8f09a935d230cdee043e10c/multi-repo/argo-app-of-apps/dev/values.yaml#L20) expects in a totally different format

      helm:
        values: |-
          ingress:
            enabled: true
            annotations:
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/tags: Environment=dev,Team=ecsdemo-frontend
              alb.ingress.kubernetes.io/target-type: ip

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version :  This is for blue-green-update example at latest commit 26c8624

- Terraform version:
Terraform v1.3.7 on linux_amd64

- Provider version(s):
- Using previously-installed hashicorp/helm v2.10.1
- Using previously-installed hashicorp/cloudinit v2.3.2
- Using previously-installed gavinbunney/kubectl v1.14.0
- Using previously-installed hashicorp/time v0.9.1
- Using previously-installed hashicorp/random v3.5.1
- Using previously-installed hashicorp/null v3.2.1
- Using previously-installed hashicorp/aws v5.11.0
- Using previously-installed hashicorp/kubernetes v2.22.0
- Using previously-installed hashicorp/tls v4.0.4

## Reproduction Code [Required]

Refer to the lines 
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/a166b8d06f38170903b99a701f0ea788916dfa4c/examples/blue-green-upgrade/modules/eks_cluster/main.tf#L116

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/a166b8d06f38170903b99a701f0ea788916dfa4c/examples/blue-green-upgrade/modules/eks_cluster/main.tf#L143

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/a166b8d06f38170903b99a701f0ea788916dfa4c/examples/blue-green-upgrade/modules/eks_cluster/main.tf#L172

## Expected behaviour

Ideally I would expect it to be something like this, which is easy to configure helm values from terraform

https://github.com/ajpaws/terraform-aws-eks-blueprints/blob/f4cbf1cbd82876e05cc8726084d3d2a71228096e/examples/blue-green-upgrade/modules/eks_cluster/main.tf#L117
https://github.com/ajpaws/terraform-aws-eks-blueprints/blob/f4cbf1cbd82876e05cc8726084d3d2a71228096e/examples/blue-green-upgrade/modules/eks_cluster/main.tf#L147
https://github.com/ajpaws/terraform-aws-eks-blueprints/blob/f4cbf1cbd82876e05cc8726084d3d2a71228096e/examples/blue-green-upgrade/modules/eks_cluster/main.tf#L179

https://github.com/ajpaws/eks-blueprints-workloads/blob/f7119054896b882e25f88fa807f93ec19636887f/multi-repo/argo-app-of-apps/dev/values.yaml#L19
https://github.com/ajpaws/eks-blueprints-workloads/blob/f7119054896b882e25f88fa807f93ec19636887f/multi-repo/argo-app-of-apps/dev/values.yaml#L39
https://github.com/ajpaws/eks-blueprints-workloads/blob/f7119054896b882e25f88fa807f93ec19636887f/multi-repo/argo-app-of-apps/dev/values.yaml#L47

## Actual behaviour

Currently the helm values from terraform are ignored or not passed to multi-repo app due to the difference in the way they are passed and the way it is expected by the multi-repo app

### PR DESCRIPTION
**Pull request by ajpaws**
# Description

### Motivation and Context

- Resolves #1722 

### How was this change tested?

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR

### CODE REVIEW

**Comment by bryantbiggs** [comment]
could we add details on what the motivation is for this change, does this fix or improve something, etc. When I first read the title I had assumed the multiple sub-directories would have been flattened to a single directory but this appears to be just helm value changes

**Comment by ajpaws** [comment]
> 

This is a fix. Currently, the 

> 

This is a fix.  currently, the helm values from [main.tf in eks_cluster](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/blue-green-upgrade/modules/eks_cluster/main.tf) module are not passed to the Application. These changes are to fix it similar to how the helm values are passed to single_repo example application

**Comment by rodrigobersa** [comment]
Hi @ajpaws!

Can you open an [Issue](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues), regarding this scenario and explain the actual vs expected behavior. Then update the comment in the Motivation and Content section.

Best,

**Comment by ajpaws** [comment]
> Hi @ajpaws!
> 
> Can you open an [Issue](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues), regarding this scenario and explain the actual vs expected behavior. Then update the comment in the Motivation and Content section.
> 
> Best,

@bryantbiggs I created the Issue https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1722

**Review by rodrigobersa — APPROVED** [review]
Thanks for the PR and the Issue @ajpaws.

**Pull request merged**
