### PR TITLE
fix: Let ingress_nginx depend on aws_load_balancer_controller (fixes #1030)

### LINKED ISSUE #1030: Nginx-Ingress should depend on AWS Loadbalancer
## Description

When setting `enable_aws_load_balancer_controller = true` and `enable_aws_load_balancer_controller = true` it is necessary to use targeted destroys to make sure the ingress is being teared down before the loadbalancer as otherwise there will be finalizers left over that cannot be resolved anymore. (see: https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/ingress-controllers/nginx)

This could be resolved by letting the ingress-nginx module explicitly depend on the load balancer module.

## Versions

- Module version: 4.12.1

- Terraform version: 1.2.9

## Reproduction Code

See: https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/ingress-controllers/nginx

## Expected behaviour

`terraform destroy` just works

## Actual behaviour

`terraform destroy` needs to be run multiple times with defined targets

### PR DESCRIPTION
**Pull request by torvitas**
### What does this PR do?

This change makes sure that if you enable the aws_load_balancer_controller and the nginx_ingress the ingress is deleted before the loadbalancer so the finalizers can be fulfilled.

### Motivation

- Resolves #1030 

### More

- [x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [x] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [x] Yes, I ran `pre-commit run -a` with this PR

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by bryantbiggs — CHANGES_REQUESTED** [review]
We don't want to add a `depends_on` across modules since it results in disruptive operations unnecessarily

**Comment by torvitas** [comment]
Code you maybe elaborate a little more what you mean by disruptive operations?

**Comment by bryantbiggs** [comment]
https://github.com/hashicorp/terraform/issues/26383#issuecomment-699149145

**Comment by bryantbiggs** [comment]
closing for now since proposed solution is not acceptable

**Pull request closed without merging**
