### PR TITLE
fix: Add local copy of Ondat due to Ondat repository migration

### LINKED ISSUE #1522: Ondat is migrating, breaking terraform init
Title says it all. 

Tried today to setup a new cluster from scratch and can't get the code from the `https://github.com/ondat/terraform-eksblueprints-ondat-addon/` repo, but it wont let me :(

### PR DESCRIPTION
**Pull request by bryantbiggs**
### What does this PR do?

- Add local copy of Ondat due to Ondat repository migration

### Motivation

- Resolves #1522

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by bryantbiggs** [comment]
yes, we'll get a patch tag up as soon as this is merged. Then we'll have to figure out what the heck happened here

**Comment by bryantbiggs** [comment]
@dcristobalhMad correct - since the source URL for Ondat is baked into the prior releases, you will need to update to at least [v4.27.0](https://github.com/aws-ia/terraform-aws-eks-blueprints/releases/tag/v4.27.0) to get around this issue. Apologies for the inconvenience, we'll need to dig in to figure out why this occurred. Going forward in v5, we will no longer have, or allow, these dependencies

**Comment by mattduguid** [comment]
We just started getting these errors in azure devops pipelines this morning for our eks blueprints solution, we switched to v4.27.0 and has resolved thanks

```
Error: Failed to download module
│ 
│ Could not download module "ondat"
│ (.terraform/modules/aws-eks-cluster.eks_blueprints_addons_core/modules/kubernetes-addons/main.tf:365)
│ source code from
│ "git::[https://github.com/ondat/terraform-eksblueprints-ondat-addon?ref=0.1.2"](https://github.com/ondat/terraform-eksblueprints-ondat-addon?ref=0.1.2%22):
│ error downloading
│ '[https://github.com/ondat/terraform-eksblueprints-ondat-addon?ref=0.1.2'](https://github.com/ondat/terraform-eksblueprints-ondat-addon?ref=0.1.2%27):
│ /usr/bin/git exited with 128: Cloning into
│ '.terraform/modules/aws-eks-cluster.eks_blueprints_addons_core.ondat'...
│ fatal: could not read Username for '[https://github.com'](https://github.com%27/): terminal prompts
│ disabled
```

**Comment by brayan9413** [comment]
Hi @bryantbiggs one question
is it going to work later? I mean unlock the repo https://github.com/ondat/terraform-eksblueprints-ondat-addon

I have an old version of EKS blueprints, it's complicated to upgrade right now

**Comment by bryantbiggs** [comment]
I don't know what is going on with the Ondat repo. What you can do in the interim is to fork the project at the version you are currently using and delete the Ondat resources from the project and use that fork for now until you can update to v4.27.0+

**Comment by prtkdave** [comment]
Is there any patch released for older version? Please let us know, older versions are failing.

**Comment by bryantbiggs** [comment]
No, there isn't any means of backporting patches to prior releases

**Comment by rkrao89** [comment]
We need a PR to update this to 4.27.0. I don't have permissions to push changes. https://github.com/awslabs/data-on-eks/blob/0641f798967599183901b0d2a2add67a3501f379/analytics/terraform/spark-k8s-operator/addons.tf#L2

**Comment by vara-bonthu** [comment]
> We need a PR to update this to 4.27.0. I don't have permissions to push changes. https://github.com/awslabs/data-on-eks/blob/0641f798967599183901b0d2a2add67a3501f379/analytics/terraform/spark-k8s-operator/addons.tf#L2

This blueprint has now been updated to use the latest V5 blueprints approach in Data on EKS. 

https://github.com/awslabs/data-on-eks/pull/170

**Pull request merged**
