### PR TITLE
feat: Add gitops support for `aws-node-termination-handler`

### LINKED ISSUE #1194: AWS Node Termination Handler - Support for ArgoCD Gitops
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
We’d like to install NTH via ArgoCD.

#### Describe the solution you would like
There is an open feature request to add NTH to the eks-blueprints-add-ons example repo here - https://github.com/aws-samples/eks-blueprints-add-ons/issues/32.

In addition to adding the argo application manifests to the add-ons repo above, it seems that the kubernetes-addons module in this repo will need an enablement of manage_via_gitops for aws-node-termination-handler.

#### Additional context
If there are no concerns with deploying NTH via ArgoCD I'd like to work on a PR to get this added. Thanks.

### PR DESCRIPTION
**Pull request by mikeinton**
### What does this PR do?
Adds GitOps enablement for AWS Node Termination Handler as per.
- Resolves #1194
- https://github.com/aws-samples/eks-blueprints-add-ons/issues/32

### More

- [x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [x] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [x] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs require a new example and/or doc page. In general:
- Use an existing example when possible to demonstrate a new addons usage
- A new docs page under `docs/add-ons/*` is required for new a new addon

### For Moderators

- [ ] E2E Test successfully complete before merge?

### Additional Notes
Confirmed that main EKS Blueprints modules handle IAM/IRSA for NTH and hands off helm chart deployment to ArgoCD in a test EKS cluster deployed from forked local copies of this repo and eks-blueprints-add-ons.

Also updated the doc for NTH to include that it is intending to be used for EKS clusters with `self_managed_node_groups` as NTH shouldn't be necessary when using EKS `managed_node_groups` as per the comments in this issue - https://github.com/aws/aws-node-termination-handler/issues/186

### CODE REVIEW

**Review by bryantbiggs — APPROVED** [review]

**Comment by mikeinton** [comment]
Thanks for merging this @bryantbiggs.

Noticed one problem here, not sure how the team wants to handle this issue.

```
│ Error: Invalid index
│
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/kubernetes-addons/locals.tf line 14, in locals:
│   14:     awsNodeTerminationHandler = var.enable_aws_node_termination_handler ? module.aws_node_termination_handler[0].argocd_gitops_config : null
│     ├────────────────
│     │ module.aws_node_termination_handler is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
make: *** [plan] Error 1
```

This code path is hit under the following conditions.

- `enable_argocd = false`
- `argocd_manage_add_ons = false`
- `enable_aws_node_termination_handler = true`
- `self_managed_node_groups` not set
- `auto_scaling_group_names = module.eks_blueprints.self_managed_node_group_autoscaling_groups` not set

I did not encounter this issue from my initial testing as my clusters are all using `enable_argocd = true`.  Today is the first time that I'm testing a new EKS cluster build with no ArgoCD/GitOps.

**Comment by mikeinton** [comment]
@oc-christopher-billett interesting, I've only seen this error when `enable_argocd = false`.  Are you using self managed node groups or managed node groups?

**Comment by oc-christopher-billett** [comment]
> @oc-christopher-billett interesting, I've only seen this error when `enable_argocd = false`. Are you using self managed node groups or managed node groups?

Managed Node Groups

**Comment by mikeinton** [comment]
@oc-christopher-billett see the doc link that was also updated in this PR - https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/docs/add-ons/aws-node-termination-handler.md#gitops-configuration

As per https://github.com/aws/aws-node-termination-handler/issues/186, Node Termination Handler isn't required for Managed Node Groups.

If you remove `enable_aws_node_termination_handler = true` or set it to false you should be good to go.

**Comment by oc-christopher-billett** [comment]
Thanks I did that anyway to carry on

**Comment by mk2134226** [comment]
HOw to fix this bug ? i am not using argo cd but want to use node termination handler

**Comment by mikeinton** [comment]
@mk2134226 are you using `self_managed_node_groups`?  Please see the add-on docs [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/docs/add-ons/aws-node-termination-handler.md#aws-node-termination-handler) on why NTH is only applicable if you're using `self_managed_node_groups`.

**Pull request merged**
