### PR TITLE
feat: Cert-manager, made configurable acme ca endpoint, added certificate resource, changed docs for cert-manager

### LINKED ISSUE #1117: [ FEATURE ] Make cert-manager CA endpoint configurable & add Certificate resource for ACME's chart.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

cert-manager module's ACME CA's endpoint is not configurable, though there are many other ACME Certificate Authority servers (OpenSSL, ZeroSSL etc.) that can replace Let's Encrypt, in the module's custom chart (both in clusterissuer-production.yaml and clusterissuer-staging.yaml) it is hard-coded to lets-encrypt's endpoint. Also if the module deploys custom chart for lets-encrypt, it only deploys the ClusterIssuer manifest, in my conviction there (in cert-manager's lets-encrypt custom chart's folder) should also be a cert-manager custom resource called 'Certificate', which will be referenced to deployed ClusterIssuer and after deploy will generate certificate.

#### Describe the solution you would like

The solution I would like is to add cert-manager's custom resource Certificate in the same chart with ClusterIssuer resource, and make ACME endpoint configurable, notice that some ACME servers require keyID and Secret for connection, which means that external account binding should also be used in ClusterIssuer's manifest.

#### Additional context

I already made that solution possible and can create a PR if this issue gets approved.

### PR DESCRIPTION
**Pull request by hakmkoyan**
### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

Creates cert-manager's custom resource Certificate in the same chart with ClusterIssuer resource, and makes ACME endpoint configurable, some ACME servers require keyID and Secret for connection, so external account binding also be used in ClusterIssuer's manifest.

### Motivation

So that the changes could be visible I created PR.
- Resolves aws-ia/terraform-aws-eks-blueprints-addons#33 

### More

- [x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [x] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs require a new example and/or doc page. In general:
- Use an existing example when possible to demonstrate a new addons usage
- A new docs page under `docs/add-ons/*` is required for new a new addon

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by hakmkoyan** [comment]
Any news?
@csantanapr 
@Zvikan 
@bryantbiggs 
@vara-bonthu
@askulkarni2

**Comment by bryantbiggs** [comment]
This is now a substantial, breaking change and will need guidance for users to migrate from existing to this new configuration

**Comment by hakmkoyan** [comment]
@bryantbiggs Changed the README.md file of [cert-manager module](https://github.com/hakmkoyan/terraform-aws-eks-blueprints/blob/feat/cert-manager/modules/kubernetes-addons/cert-manager/README.md). Added the `Migration to newer version` part, where every possible change is described. Please review.

**Comment by hakmkoyan** [comment]
@bryantbiggs What's new? Is this going to be applied in blueprints' major update?

**Comment by hakmkoyan** [comment]
Hi, any news on this PR? this is already the 3rd month there is no reply?!
@csantanapr
@Zvikan
@bryantbiggs
@vara-bonthu
@askulkarni2

**Comment by hakmkoyan** [comment]
@csantanapr
@Zvikan
@bryantbiggs
@vara-bonthu
@askulkarni2

**Comment by hakmkoyan** [comment]
Any news on this?
@bryantbiggs

**Comment by hakmkoyan** [comment]
@bryantbiggs I can change configuration to use my official custom helm chart repository to avoid breaking changes, so that user could be able to choose which config it wants.

**Comment by bryantbiggs** [comment]
thank you for the PR - this will be resolved in the new addons module https://github.com/aws-ia/terraform-aws-eks-blueprints-addons

**Pull request closed without merging**
