### PR TITLE
Pass through "key_name" TF var to enable SSH access on custom launch templates

### PR DESCRIPTION
**Pull request by cjbaar**
### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

Enables SSH access to worker nodes create with custom launch templates (`create_launch_template=true`). Makes use of existing `key_name` variable in the terraform `aws_launch_template` resource.

### Motivation

Required SSH access to nodes, and EKS does not allow the use of the standard "remote_access" block when using custom launch templates.

### More

- [x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [x] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by askulkarni2 — CHANGES_REQUESTED** [review]
@cjbaar please follow the community guidelines to open an issue first. This change may not be required as SSM is the preferred method of accessing worker nodes. You can setup with SSM over an SSH connection as described [here](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html)

**Comment by bryantbiggs** [comment]
This will be completed in #749

**Comment by cjbaar** [comment]
Thanks @bryantbiggs. Is there a rough timeline for that task? Seems like a pretty sizable change.

**Comment by bryantbiggs** [comment]
closed in #749 which will be released under v5.0 soon

**Pull request closed without merging**
