### PR TITLE
feat: Appmesh prometheus (Terraform & ARgoCD) & Appmesh controller with ArgoCD

### LINKED ISSUE #1212: New Addon appmesh-prometheus
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Prometheus is an open-source monitoring and alerting toolkit which is able to scrape metrics from specified targets at configured intervals. You can use Prometheus with AWS App Mesh to track metrics of your applications within the meshes.

App Mesh provides a basic installation to setup Prometheus quickly using Helm. Follow the steps below to install the pre-configured version of Prometheus which works with App Mesh.

#### Describe the solution you would like

A simple EKS Blueprint Add-on to deploy AppMesh

```
  enable_appmesh_prometheus = true
```

#### Describe alternatives you have considered
Manual installation

Add the EKS repository:
```
helm repo add eks https://aws.github.io/eks-charts
```
Install App Mesh Prometheus:
```
helm upgrade -i appmesh-prometheus eks/appmesh-prometheus \
    --namespace appmesh-system
```

### PR DESCRIPTION
**Pull request by allamand**
### What does this PR do?

Add Addon for AppMesh Prometheus and Fix deployment for AppMesh Controller through ArgoCD

- https://docs.aws.amazon.com/app-mesh/latest/userguide/metrics.html
- https://artifacthub.io/packages/helm/aws/appmesh-prometheus

### Motivation

- Resolves aws-ia/terraform-aws-eks-blueprints-addons#52
- https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1400

### More

- [x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [x] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [x] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs require a new example and/or doc page. In general:
- Use an existing example when possible to demonstrate a new addons usage
- A new docs page under `docs/add-ons/*` is required for new a new addon

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by allamand** [comment]
TODO: Need also to create and test when deploying with ArgoCD

**Comment by Zvikan** [comment]
if this is still WIP lets convert this PR to draft, will help us focus on PRs that considered ready, thanks!

**Comment by allamand** [comment]
Actually We have an example that showcase deployment with Terraform here : https://github.com/aws-samples/amazon-eks-argo-rollouts

I have also a version deploying with ArgoCD. Not sure if this needs additional example in this repo ?

**Comment by allamand** [comment]
Link to the Add-on PR : https://github.com/aws-samples/eks-blueprints-add-ons/pull/142

**Comment by bryantbiggs** [comment]
thank you but at this time we will not be expanding support for AppMesh related addons

**Pull request closed without merging**
