### PR TITLE
added managed prometheus alert manager config for java/jmx modules. A…

### PR DESCRIPTION
**Pull request by rameshv29**
…dded additional output variable to get the managed prometheus workspace id

### What does this PR do?

added managed prometheus alert manager config for java/jmx modules. Added additional output variable to get the managed prometheus workspace id
### More

- [x ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by askulkarni2 — CHANGES_REQUESTED** [review]
Hi @rameshv29, thanks for the PR. Looking good.

Please run `pre-commit run -a` and then commit + push any changes.

**Comment by rameshv29** [comment]
@askulkarni2 - ran pre-commit and updated the PR. can you pls review and approve?

**Review by vara-bonthu — APPROVED** [review]
LGTM

**Review by bryantbiggs — APPROVED** [review]
Thank you @rameshv29 !

**Pull request merged**
