### PR TITLE
[v5] refactor: remove kms key

### LINKED ISSUE #460: [FEATURE]  `aws-for-fluentbit` - Make it possible to pass in additional ARNs that should have `kms:*` in the key policy.
#### Is your feature request related to a problem? Please describe

Managing KMS keys is tricky and various missteps can cause Keys to become unmanageable. All KMS key policies should at a minimum make it easy to pass in a list of ARNs that have full KMS access.

Even better, would be some flexibility to add a list of ARNs to each section.

Something that basically works like this recent PR into the core part of the repo.
https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/414

#### Describe the solution you'd like
There is a `cluster_kms_key_additional_admin_arns`, so maybe add something like an `addon_fleuntbit_kms_key_additional_admin_arns` variable to accomplish the same task.

It might even make sense to support a `global_kms_key_additional_admin_arns` that when set would be added to all key policies.

#### Describe alternatives you've considered
Nothing. I just want more control over the key policy, in case of emergency, etc.

### LINKED ISSUE #494: [FEATURE] Add some easy to see cautionary notes and helpful hints around KMS usage in the README & examples
#### Is your feature request related to a problem? Please describe

After helping out with this https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/485 and having had a similar issue early on here https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/414

It might be good to make sure that people using this module are aware of the basics of KMS and how they can protect themselves from unmanageable keys. It really is a pain when this happens, especially when you aren't really familiar with KMS and all of a sudden find yourself with a terraform stack that can't be easily destroyed and replaced.

#### Describe the solution you'd like

Add some very easy-to-discover documentation in the README and default examples for new users with a few warnings, and explanations of best practices, and bad outcomes.

### LINKED ISSUE #752: Replace KMS key module
#### Is your feature request related to a problem? Please describe
- Replace the local implementation of KMS key module with the implementation provided by the [`terraform-aws-eks`](https://github.com/terraform-aws-modules/terraform-aws-eks) and [`terraform-aws-kms`](https://github.com/terraform-aws-modules/terraform-aws-kms) modules 

#### Describe the solution you'd like
- The local KMS key module is removed
- The EKS module used in this project is updated to use the KMS key configurations provided by it for creating cluster keys
- The `aws-for-fluentbit` module is updated to use the [`terraform-aws-kms`](https://github.com/terraform-aws-modules/terraform-aws-kms)

#### Additional context
- Changes that users need to make when upgrading from v4.x to v5.x need to be added to the upgrade guide

### PR DESCRIPTION
**Pull request by Zvikan**
### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

 - Replace the local implementation of KMS key module with the implementation provided by the [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) and [terraform-aws-kms](https://github.com/terraform-aws-modules/terraform-aws-kms) modules
### Motivation
- Closes #460
- Closes #494
- Closes #752

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by Zvikan** [comment]
Moving from draft to ready for review, going through CI checks.

**Comment by bryantbiggs** [comment]
updated to make sure it goes into `refactor/v5` branch and not `main`

**Comment by Zvikan** [comment]
Hold off reviewing this for now, I have found out another scenario with aws for fluentbit addon which requires more work and testings.

**Comment by Zvikan** [comment]
Can be reviewed again; addressed the KMS alias issues by using new release of the upstream module (thanks @bryantbiggs !)
Plan examples workflow is green and happy now - https://github.com/aws-ia/terraform-aws-eks-blueprints/actions/runs/2876655268

**Review by bryantbiggs — APPROVED** [review]

**Pull request merged**
