### PR TITLE
feat: Add Karpenter new NTH IAM policies

### LINKED ISSUE #1175: Upgrades for karpenter v0.19.1
Things that need upgrade:
1. Helm chart version upgrade
2. Native Spot Termination Handling IRSA policy update ([#2546](https://github.com/aws/karpenter/pull/2546))
3. Update [values.yaml](https://github.com/aws/karpenter/blob/main/charts/karpenter/values.yaml#L129-L161) for `karpenter-global-settings`

### PR DESCRIPTION
**Pull request by FernandoMiguel**
### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

The next version of Karpenter adds support for NTH: https://github.com/aws/karpenter/pull/2546/files

This PR adds the IAM changes to this module.
A future PR will add the ConfigMap and SET changes, once the release is done, so I can test.

### Motivation

- Resolves #1175

### More

- [X] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs require a new example and/or doc page. In general:
- Use an existing example when possible to demonstrate a new addons usage
- A new docs page under `docs/add-ons/*` is required for new a new addon

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by askulkarni2** [comment]
@FernandoMiguel please open an issue. And can we please do 1 PR for the NTH feature when its ready?

**Comment by FernandoMiguel** [comment]
Will do.

**Comment by askulkarni2** [comment]
Hi @FernandoMiguel Karpenter v0.19.0 has been released! Let's get this PR up-to-date with the required changes. I've documented them in #1175. Please have a look and let me know if I am missing anything.

**Comment by FernandoMiguel** [comment]
@askulkarni2 already have the values.yaml changed locally, so should be easy to test against this branch.
There are a few new IAM policies that I need to add, that were added this week.
Will try to get something tomorrow.
I'll be on call from Friday so I'll be away from eks work, sadly.

**Comment by FernandoMiguel** [comment]
merged @andrewhibbert branch into mine, since they add already all the code for the settings bit

**Comment by askulkarni2** [comment]
Hi @FernandoMiguel I do not see @andrewhibbert's changes in your PR.

**Comment by FernandoMiguel** [comment]
It's in the locals

**Comment by FernandoMiguel** [comment]
waiting on a review.
thanks

**Comment by FernandoMiguel** [comment]
Hi team,
can I get a new review pls?
thanks

**Comment by FernandoMiguel** [comment]
Hi team,
can I get a new review pls?
thanks

**Review by bryantbiggs — APPROVED** [review]

**Pull request merged**
