### PR TITLE
chore: Removed examples which are now moved to data on EKS

### PR DESCRIPTION
**Pull request by vara-bonthu**
### What does this PR do?

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

Removed EMR on EKS and EMR with FSx patterns from Blueprints. These blueprints available maintained under Data on EKS repo. All the data related patterns will be available in Data on EKS repo. AWS blogs are now redirected to use the new repo links. 

New Location
- https://awslabs.github.io/data-on-eks/docs/amazon-emr-on-eks/emr-eks-fsx-for-lustre

### Motivation

- Resolves #1162

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs require a new example and/or doc page. In general:
- Use an existing example when possible to demonstrate a new addons usage
- A new docs page under `docs/add-ons/*` is required for new a new addon

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by bryantbiggs — APPROVED** [review]
feel free to move the EMR on EKS Fargate if that one is also in the DoEKS project already

**Comment by vara-bonthu** [comment]
Nice! Will move the Fargate example to DoEKS repo. Need to think about best way to manage EMR on EKS module.

**Comment by vara-bonthu** [comment]
We can merge this for now. I will create an another PR for moving `EMR on EKS Fargate` blueprint to Data on EKS and to EKS Blueprints

**Comment by vara-bonthu** [comment]
Will raise a new PR to avoid these merge issues.

**Pull request closed without merging**
