### PR TITLE
fargate only example with monitoring and logging solutions

### PR DESCRIPTION
**Pull request by season1946**
### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [x] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by season1946** [comment]
It is an example for Fargate only cluster with monitoring and logging solutions. Detailed info can be found at readme at https://github.com/season1946/terraform-aws-eks-blueprints/tree/main/examples/observability/fargate-metric-logging

**Comment by season1946** [comment]
@askulkarni2 this pr is for demoing the monitoring and logging solutions for Fargate only cluster. I wrote an email about this idea before which was inspired with our cases in Data lab. Could you please review and let me know your opinion? thanks.

**Comment by bryantbiggs** [comment]
hi @season1946 - can we start with an issue to describe what the goal(s) are, the problem(s) we are solving for, etc. before jumping into a PR? We do have an existing Fargate example that we can leverage as well instead of a net new example for this. Once the details are fleshed out we can look at re-opening this PR or a new one. Thanks!

**Comment by season1946** [comment]
@bryantbiggs thanks for the feedback. 
This example is for demoing monitoring and logging solutions for EKS Fargate only cluster. I see we have a similar example at
https://github.com/season1946/terraform-aws-eks-blueprints/tree/main/examples/observability/amp-amg-opensearch
But that one is for EC2 based EKS cluster. Since some unique features in fargate, that solution cannot be applied to Fargate directly. Below is the intro of our example. The focus is on observability and that is why I put it under /examples/observability/. please let me know your opinion. thanks.

"Running EKS cluster under pure serverless mode is attracting more and more attention recently for cost reduction and administration work offload. However, it is not an easy job to provision such a cluster with well-equipped monitoring and logging solutions. User has to search around to get different open source kubernetes components working on Fargate. In this example, we will walk through a way using EKS blueprints and ArgoCD to quickly provision a fargate only EKS cluster. It will also equip the cluster with Fluent bit and Amazon OpenSearch as logging solution, and use AWS Distro for OpenTelemetry (ADOT), Amazon Managed Service for Prometheus (AMP) for monitoring"

**Pull request closed without merging**
