### PR TITLE
feat: Add kubernetes_timeouts variable.

### PR DESCRIPTION
**Pull request by kahirokunn**
### What does this PR do?

add "timeouts" option for kubernetes resources.

### Motivation

Due to a variety of factors, resource creation often does not complete within the default timeouts.

### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [x] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by kahirokunn** [comment]
@Zvikan How about this feature? If you like, I will add examples and resolve conflicts.

**Comment by bryantbiggs** [comment]
@kahirokunn could you elaborate on this statement
> Due to a variety of factors, resource creation often does not complete within the default timeouts.

What are the factors? How are you applying the resources (apply entire example with `terraform apply` or targetted applies with `terraform apply -target=module.vpc && terraform apply -target=module.eks_blueprints && ...`)?

**Comment by kahirokunn** [comment]
@bryantbiggs 

I use Terraform Cloud.
From my research, the Terraform Cloud runner is located in us-east-1.
My AWS region is ap-northeast-1.
The distance from us-east-1 to ap-northeast-1 is 6752 miles.
Also, the Terraform Cloud runner is quite poor and network bandwidth is limited.
For these reasons, it cannot be completed within the default timeout period.

The only way to reproduce the timeout is to create a kubernetes resource using Terraform Cloud on an EKS cluster in a region that is over 5000 miles away from us-east-1.
I have tried over 1000 times and it always times out.

Is there any additional information you need?
Thx.

**Comment by kahirokunn** [comment]
Hello 👀

**Comment by kahirokunn** [comment]
Hello 👀  😢

**Comment by kahirokunn** [comment]
@vara-bonthu Hello! Could you please review it? 🙇

**Comment by kahirokunn** [comment]
@Zvikan Hello! Could you please review it? 🙇

**Comment by reoring** [comment]
Hi there. Could I tell about that why this PR doe's not review by anyone? I'm encountered to same problem. Please review it.

**Comment by nahum-landa** [comment]
@bryantbiggs im having the same issue., seems it is caused by slow VPN.

**Pull request closed without merging**
