### PR TITLE
feat: Add pattern for VPC CNI native network policy support

### LINKED ISSUE #1747: Add example for Amazon VPC CNI Network Policy feature
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Amazon announced native Network Policy support through Amazon VPC CNI (https://aws.amazon.com/about-aws/whats-new/2023/08/amazon-vpc-cni-kubernetes-networkpolicy-enforcement/). Adding an example how to use Network Policies with Amazon VPC CNI helps user to get started.

#### Describe the solution you would like

Add TF code (inside examples folder) how to use Network Policies with Amazon VPC CNI

#### Describe alternatives you have considered

N/A

### PR DESCRIPTION
**Pull request by valentinwidmer**
# Description

### Motivation and Context

- Resolves #1747 

### How was this change tested?

- [X] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [ ] Yes, I ran `pre-commit run -a` with this PR

### Additional Notes

- Tested in a fresh AWS Account

### CODE REVIEW

**Comment by rodrigobersa** [comment]
Hi @valentinwidmer!

Thanks for the PR. I’ll review and get back to you soon.

**Review by rodrigobersa — CHANGES_REQUESTED** [review]
Thank you @valentinwidmer!!

Please update the `docs/patterns` using the same standards of the other patterns [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs/patterns).

Also, run the pre-commit scripts against your files to fix any formatting and lint for the CI tests. `pre-commit run --files ./patterns/aws-vpc-cni-network-policy/*`

**Comment by valentinwidmer** [comment]
> Thank you @valentinwidmer!!
> 
> Please update the `docs/patterns` using the same standards of the other patterns [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs/patterns).
> 
> Also, run the pre-commit scripts against your files to fix any formatting and lint for the CI tests. `pre-commit run --files ./patterns/aws-vpc-cni-network-policy/*`

Added documentation and executed pre-commit scripts

**Review by rodrigobersa — APPROVED** [review]
Awesome!

**Pull request merged**
