### PR TITLE
Added Datadog Addon

### PR DESCRIPTION
**Pull request by nayaksuraj**
### What does this PR do?

In this pr, I have added datadog agent as a new addon to eks blueprint.

### Motivation

I am moving cluster creations and addon management to terraform eks blueprint and found datadog is not there as addon. So I thought I should add.

### More

- [x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples) to support my PR
- [x] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/eks-blueprints-add-ons) repo (if applicable)
- [x] Yes, I have updated the [docs](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs require a new example and/or doc page. In general:
- Use an existing example when possible to demonstrate a new addons usage
- A new docs page under `docs/add-ons/*` is required for new a new addon

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by bryantbiggs** [comment]
duplicate of #882

**Comment by nayaksuraj** [comment]
Hi @bryantbiggs one is helm based and the other is operator based.

**Comment by sotoiwa** [comment]
Hi @bryantbiggs since Datadog Operator is still public beta, I think it's better to have helm option.
https://docs.datadoghq.com/containers/kubernetes/installation/?tab=operator#minimum-agent-and-cluster-agent-versions

**Comment by tsndqst** [comment]
The Datadog Operator documentation itself recommends the Datadog Helm install method.  https://github.com/DataDog/datadog-operator#datadog-operator-vs-helm-chart

One disadvantage of the Operator is that the Datadog agent is not deployed until a `DatadogAgent` resource is created.  Terraform doesn't have a resource for `DatadogAgent` so a `kubernetes_manifest` resource would need to be used.  `kubernetes_manifest` requires access to the k8s API during planning so it cannot be used without creating the cluster first.  Using the helm method should be able to be used in the same TF run as cluster creation.

**Comment by tsndqst** [comment]
@bryantbiggs any chance this can re-opened? I'd rather not re-implement this if this PR has working code.

**Comment by bryantbiggs** [comment]
Thank you for the PR @nayaksuraj   - since this is just simply a wrapper of the Datadog helm chart, I would suggest using the `helm_release` resource directly to deploy. At this time, we won't be adding this as a supported addon

**Pull request closed without merging**
